### ISSUE TITLE
After restarting maubot the socialmediabot does not reply until changing/saving configuration

### ISSUE THREAD

**Issue by weebl2000** [ggogel/SocialMediaDownloadMaubot#6]
Anyone else notice this?

My config:

```
reddit:
    enabled: false
    info: false
    image: true
    video: true
instagram:
    enabled: true
    info: true
    image: true
    thumbnail: false
    video: true
youtube:
    enabled: false
    info: true
    thumbnail: true

```

Somehow after restarting maubot the socialmediabot does not reply anything until I save the config after changing something. You do see it presencing right after the links are posted, so it seems something gets triggered, just execution fails. Logs do not show anything useful.

**Comment by ggogel** [comment]
Ah, got it. Here's a more personalized response:

Hi there,

Thanks for pointing out this issue. I've looked into it and have fixed the bug in the latest release.

You should now be able to restart maubot without having to make additional changes to the config for the bot to respond. Please update to the latest version and let me know if you run into any more issues.

**Comment by weebl2000** [comment]
> Ah, got it. Here's a more personalized response:
> 
> Hi there,
> 
> Thanks for pointing out this issue. I've looked into it and have fixed the bug in the latest release.
> 
> You should now be able to restart maubot without having to make additional changes to the config for the bot to respond. Please update to the latest version and let me know if you run into any more issues.

Hi Gerrit,

Thank you for the update. Will try it out and let you know. :)

I was mainly wondering if it was just me that encountered this problem or if it was more widespread. I would have dived deeper and debug if it was just me <3.

-weebl

**Comment by weebl2000** [comment]
@ggogel 

Works like a charm now! Thanks for fixing.

btw: Had to package the zip myself, there are no assets published for 1.0.1 (only source)- maybe the github action isn't publishing the artifact correctly?

**Comment by ggogel** [comment]
At first I planned to package the assets through the action but it's actually not necessary since Github seems to automatically zip the source code for every release and puts them under assets.

**Comment by ggogel** [comment]
Never mind, it puts it into a subfolder. I'll update the release action.
