### ISSUE TITLE
Feature: Add Support for Reddit Image Galleries

### ISSUE THREAD

**Issue by HarHarLinks** [ggogel/SocialMediaDownloadMaubot#8]
currently, receiving a link such as https://www.reddit.com/r/comics/comments/w43gr2/swap_oc/ (comments thread to a gallery) crashes at https://github.com/ggogel/SocialMediaDownloadMaubot/blob/2a8ec8b3853c7085604a4ebb0ab63c383daa16b5/socialmediadownload.py#L253

i think the plugin is unable to detect that its dealing with a gallery and can't handle that. then again, i'm not sure if galleries should be supported in the bot and if so then how.

**Comment by ggogel** [comment]
Implemented in version 1.4.0
